# Generated by Django 4.2.3 on 2023-07-09 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinemax', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField(default=0)),
                ('movie_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='transactions',
            name='transaction_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
        migrations.AddField(
            model_name='user_seat',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinemax.ticket'),
        ),
    ]
