# Generated by Django 4.2.3 on 2023-07-09 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinemax', '0002_user_seat_transactions_transaction_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transactions',
            new_name='Transaction',
        ),
    ]
