# Generated by Django 4.2.3 on 2023-07-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemax', '0003_rename_transactions_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('age_rating', models.IntegerField()),
                ('poster', models.URLField()),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
