# Generated by Django 4.2.3 on 2023-07-11 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemax', '0005_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='user_seat',
            name='ticket',
        ),
        migrations.AddField(
            model_name='ticket',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='seats',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='User_seat',
        ),
    ]
