# Generated by Django 4.2.3 on 2023-07-11 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemax', '0007_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
